# Generated by Django 2.0.7 on 2019-03-27 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teammembers', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teammember',
            name='trash',
        ),
    ]
