# Generated by Django 2.0.7 on 2019-04-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teammembers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='delete',
            field=models.CharField(blank=True, default=False, max_length=120, null=True),
        ),
    ]
