# Generated by Django 2.0.7 on 2019-04-02 02:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teammembers', '0002_teammember_delete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teammember',
            old_name='delete',
            new_name='delet',
        ),
    ]
